### ISSUE TITLE
hal-0.4.7 enabled wai-handler-hal-0.1.0.0

### ISSUE THREAD

**Issue by endgame** [Nike-Inc/hal#89]
@IamfromSpace I said earlier that I needed the features in hal-0.4.7 to release something. That something is: https://github.com/bellroy/wai-handler-hal , and the fixed runtime functions let me write `runWithContext`.

No action required here, just wanted to show you the fruits.

**Comment by endgame** [comment]
TYVM for your help.

**Comment by IamfromSpace** [comment]
This is awesome!  This seems like it enables a ton of stuff!  I’ve gotta dive into this and try it out.

I’m thinking it might make sense for the hal README to point you to this too.  Something like, “if your looking to do X” kind of section.

Looking forward to using this!

**Comment by endgame** [comment]
> I’m thinking it might make sense for the hal README to point you to this too. Something like, “if your looking to do X” kind of section.

If the hal README marks it as "a" way and not "the" way to handle API Gateway Proxy events, that'd be cool.
